language: php

php:
    - 8.1

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script: vendor/bin/pest --coverage --min=100

after_success:
    - travis_retry php vendor/bin/php-coveralls
